from glob import glob
from pathlib import Path
files = glob(".\\dist\\main\\**\\*",recursive=True)
__name__ = "ForTeraterm"

initxt = f"""; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; Basic setup information
AppName={__name__}
AppVersion=1.0
DefaultDirName={{pf}}\{__name__}
DefaultGroupName={__name__}
OutputDir=Output
OutputBaseFilename=Setup{__name__}
Compression=lzma
SolidCompression=yes

[Files]
; The main executable file generated by PyInstaller
Source: "dist\main\main.exe";  DestDir: "{{app}}"; Flags: ignoreversion
"""
files = [f.replace(".\\","") for f in files if f!='.\\dist\\main\\main.exe']
for f in files:
    tmp_files = glob(f'{f}\\*')
    flag = 0
    for tf in tmp_files:
        p = Path(tf)
        if p.is_file():
            flag += 1
    if flag == 0:
        continue
    p = Path(f)
    if p.is_dir():
        tmp_path = f.replace("dist\\main","")
        initxt += f'Source: "{f}\\*"; DestDir: "{{app}}{tmp_path}"\n'
initxt += f'Source: "dist\\main\\README.pdf"; DestDir: "{{app}}\\"\n'
initxt+=f"""
[Icons]
; Create a shortcut in the Start Menu
Name: "{{group}}\{__name__}"; Filename: "{{app}}\main.exe"
"""
with open("mkinst.iss","w",encoding="utf-8") as f:
    f.write(initxt)