"""Generate the Inno Setup script for the Windows installer.

This script mirrors the manual build steps that used to live in ``build.bat``
and is invoked from the GitHub Actions workflow as part of the release
pipeline.  The previous implementation relied on Windows specific glob
patterns and only added directories that contained files directly under
them.  In the CI environment the generated ``mkinst.iss`` sometimes missed
critical directories (such as ``_internal``), which meant the installer could
not be compiled successfully.  The new implementation enumerates the contents
of ``dist/main`` using :mod:`pathlib` so that it works reliably on every
platform and always lists every directory that PyInstaller generates.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable


APP_NAME = "ForTeraterm"
DIST_ROOT = Path("dist") / "main"
MAIN_EXECUTABLE = "main.exe"


def _to_windows_path(path: Path) -> str:
    """Return ``path`` formatted with Windows path separators."""

    return str(path).replace("/", "\\")


def _iter_top_level_directories(base: Path) -> Iterable[Path]:
    """Yield the immediate child directories under ``base`` sorted by name."""

    return sorted(p for p in base.iterdir() if p.is_dir())


def _iter_top_level_files(base: Path) -> Iterable[Path]:
    """Yield the immediate child files under ``base`` sorted by name."""

    return sorted(p for p in base.iterdir() if p.is_file())


def _build_files_section() -> str:
    if not DIST_ROOT.exists():
        raise FileNotFoundError(
            "PyInstaller output was not found. Did you run 'pyinstaller main.spec'?"
        )

    lines: list[str] = [
        '; The main executable file generated by PyInstaller',
        f'Source: "{_to_windows_path(DIST_ROOT / MAIN_EXECUTABLE)}";  '
        'DestDir: "{app}"; Flags: ignoreversion',
    ]

    for file_path in _iter_top_level_files(DIST_ROOT):
        if file_path.name.lower() == MAIN_EXECUTABLE:
            continue
        lines.append(
            f'Source: "{_to_windows_path(file_path)}"; DestDir: "{app}"; '
            'Flags: ignoreversion'
        )

    for directory in _iter_top_level_directories(DIST_ROOT):
        relative = _to_windows_path(directory.relative_to(DIST_ROOT))
        dest_dir = rf"{{app}}\{relative}"
        lines.append(
            f'Source: "{_to_windows_path(directory)}\\*"; DestDir: "{dest_dir}"; '
            'Flags: ignoreversion recursesubdirs createallsubdirs'
        )

    return "\n".join(lines)


def build_script() -> str:
    files_section = _build_files_section()
    return (
        "; Script generated by the Inno Setup Script Wizard.\n"
        "; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!\n\n"
        "[Setup]\n"
        "; Basic setup information\n"
        f"AppName={APP_NAME}\n"
        "AppVersion=1.0\n"
        f"DefaultDirName={{pf}}\\{APP_NAME}\n"
        f"DefaultGroupName={APP_NAME}\n"
        "OutputDir=Output\n"
        f"OutputBaseFilename=Setup{APP_NAME}\n"
        "Compression=lzma\n"
        "SolidCompression=yes\n\n"
        "[Files]\n"
        f"{files_section}\n\n"
        "[Icons]\n"
        "; Create a shortcut in the Start Menu\n"
        f"Name: \"{{group}}\\{APP_NAME}\"; Filename: \"{{app}}\\{MAIN_EXECUTABLE}\"\n"
    )


def main() -> None:
    mkinst_contents = build_script()
    Path("mkinst.iss").write_text(mkinst_contents + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
